export const Data = [
  {
    id: "26",
    name: "Vải a ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "27",
    name: "Vải b ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "30",
    name: "Vải c ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "4",
    name: "Vải d ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "5",
    name: "Vải e ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "6",
    name: "Vải e ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "7",
    name: "Vải e ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "8",
    name: "Vải e ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
  {
    id: "9",
    name: "Vải e ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum leo ex, non ullamcorper velit placerat ut. Nunc varius urna ultrices arcu faucibus, ut fringilla magna suscipit. Sed ac eleifend nunc, vel maximus magna. Ut iaculis dolor vel convallis convallis. Phasellus ex quam, lobortis non varius eget, viverra vitae urna. Etiam convallis nunc diam, euismod commodo erat venenatis vitae. Morbi vestibulum sagittis varius. Ut volutpat ex eu purus pulvinar, sed congue nisi tempus. Nam sed metus id quam elementum malesuada quis ullamcorper enim. Cras pulvinar eleifend vestibulum. Morbi dapibus euismod eros quis malesuada. Maecenas eget commodo neque, ac mattis velit.",
    material: "Cotton",
    origin: "China",
    width: "143",
    weight: "194",
    color: "đỏ",
    price: "20000",
  },
];
